tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "colordiff"
brew "coursier/formulas/coursier"
brew "curl"
brew "dep"
brew "docker", link: false
brew "emacs"
brew "gibo"
brew "git"
brew "git-secrets"
brew "glide"
brew "go"
brew "hugo"
brew "jq"
brew "mkcert"
brew "netcat"
brew "nmap"
brew "nss"
brew "openssl@1.1"
brew "peco"
brew "python"
brew "readline", link: true
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "ruby-build"
brew "rustup"
brew "rust-analyzer"
brew "sbt"
brew "scalacenter/bloop/bloop"
brew "tfenv"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

cask "alfred"
cask "chromedriver"
cask "clipy"
cask "docker"
cask "firefox"
cask 'google-chrome'
cask "wireshark"
cask "google-cloud-sdk"
